scheduler.bucketReader.cron-expression = ${INTEROP_SCHEDULER_BUCKETREADER_TIMER}
scheduler.bucketReader.active = ${INTEROP_SCHEDULER_BUCKETREADER_ACTIVE}

#Bucket
amazon.clientS3.accesskey = 
amazon.clientS3.secretkey = 
amazon.clientS3.region = ${AWS_BUCKET_REGION}
amazon.bucketS3.name =
amazon.bucketS3.key =
