#Scheduler
scheduler.bucketReader.daily-hours = 17
scheduler.bucketReader.daily-minutes = 30
scheduler.bucketReader.active = true
scheduler.bucketReader.retry-initial-interval = 60
scheduler.buckerReader.retry-interval-multiplier=1.5


#Bucket
amazon.clientS3.accesskey = accesskey
amazon.clientS3.secretkey = secretkey
amazon.clientS3.region = us-east-1
amazon.bucketS3.name = bucket-name
amazon.bucketS3.key = bucket-key